#!/usr/bin/env bash
# Configure nginx to run as nginx user on port 8080

sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:80/listen [::]:8080/g' /etc/nginx/sites-enabled/default

pkill nginx 2>/dev/null
sleep 1
nginx

pgrep -a nginx
