#!/usr/bin/env bash
# Configure nginx to run as nginx user on port 8080

sed -i 's/^user [a-z-]*/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080/g' /etc/nginx/sites-enabled/default

service nginx start
sleep 1
pgrep -l nginx
