#!/usr/bin/env bash
# Bash script that installs HAProxy & makes configurations

sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get -y install haproxy

echo "ENABLED=1" >> /etc/default/haproxy

printf %s "listen webs
    bind *:80
    mode http
    balance roundrobin
    server 7028-web-01 44.211.76.97 check
    server 7028-web-02 13.218.144.213 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
